# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "XPerience sepolicy"
SPDX-PackageSupplier = "The XPerience Project"
SPDX-PackageDownloadLocation = "https://github.com/TheXPerienceProject/android_device_xperience_sepolicy"

[[annotations]]
path = ["atv/**", "common/**", "exynos/**", "libperfmgr/**", "qcom/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "The XPerience Project"
SPDX-License-Identifier = "Apache-2.0"
